# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user=User.create!(:email=>'test@test.com',:password=>'password')

post=Post.create!(:title=>'Up and running',:content=>'This post has been generated by the site for testing purposes. I hope you can read this!',:published=>'2014-08-11 00:00:00 UTC',:author=>'The Shibe in the Machine')